### ISSUE TITLE
pamu2fcfg - opensk not returns x5c

### ISSUE THREAD

**Issue by Nassiel** [google/OpenSK#275]
## Expected Behavior
After using pamu2fcfg you get the pam configuration file

## Actual Behavior
error: fido_cred_verify (-7) FIDO_ERR_INVALID_ARGUMENT

## Steps to Reproduce the Problem

1. pamu2fcfg
1. Introduce my device pin
1. Push the button

## Specifications

- Version: pam_u2f 1.1.0
- Platform: Archlinux 5.10.10

## Extra information
While doing the debug, I see that the x5c=(nil)
```fido_cred_verify: cdh=0x55da2ccd34f0, authdata=0x55da2cce9210, x5c=(nil), sig=0x55da2ccd57f0, fmt=0x55da2ccd5a40 id=0x55da2ccd5e80, rp.id=pam://<hostname>```

**Comment by kaczmarczyck** [comment]
Hi, thanks for opening. The default configuration in OpenSK is to use self-attestation (instead of batch attestation). This was noted in an [issue in pam-u2f](https://github.com/Yubico/pam-u2f/pull/168). They seem to provide a fix on their next release. In the meantime, you have two options:

- You build the latest pam-u2f from GitHub, instead of their latest release. (I tested, it works.)
- (Discouraged!) You build OpenSK with batch attestation by changing [this constant](https://github.com/google/OpenSK/blob/b0c1b73897816edb757a163943f7b36a55f76a19/src/ctap/mod.rs#L77) to `true`, then proceeding setup as normal. Warning: Using batch attestation has privacy implications. It makes you uniquely identifiable and your accounts can be linked. This mode is intended for vendors that sell large batches of security keys with the same attestation key material.

I propose this issue can be closed without any action?

**Comment by Nassiel** [comment]
Smoothly working with the latest git version. Thank you very much, very well explained and helpful!
