### ISSUE TITLE
Add code coverage tracking

### ISSUE THREAD

**Issue by ebursztein** [google/OpenSK#337]
## Expected Behavior

Have each merge request produce a code coverage report tracked over time via https://coveralls.io/github/google/

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by jmichelp** [comment]
I did a quick investigation.
Corresponding Github actions exist so this doesn't seem too hard.
I configured and enabled coveralls for this repository.

What's next:
- [x] write Github workflow
- [x] write grcov configuration
- [x] test
- [x] create PR

Rust code should be compiled with specific options and unfortunately, this doesn't seem to compile:
```
  = note: clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
          Undefined symbols for architecture x86_64:
            "_libtock_alloc_init", referenced from:
                _rust_start in liblibtock_core-7e139524ee594146.rlib(libtock_core-7e139524ee594146.libtock_core.7k5hr3h7-cgu.0.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Edit: it seems the above error is due to the Rust compilation flag: `-Clink-dead-code` which is problematic.

**Comment by jmichelp** [comment]
The `develop` branch is covered by the fix but the badge doesn't point to the correct branch.
And it needs a follow-up PR for the `stable` branch
