### ISSUE TITLE
support TOTP / HOTP

### ISSUE THREAD

**Issue by ghost** [google/OpenSK#711]
support TOTP / HOTP like canokey

**Comment by jmichelp** [comment]
TOTP, as the name suggests, would require a time reference, which means adding a battery to the nRF52 so that it can keep its RTC powered. So it's unlikely to happen.

HOTP would be possible but as there's no standard way to configure hardware with it, it would require to also write a manager application, that works across platforms, potentially including mobile app too. That's a much more significant amount of work (including increased support requests from people using this feature) for little added value in terms of security. It would also require to emulate a keyboard, which is doable but again not necessarily desirable from a security point of view.

That being said, we welcome contributions and would happily review pull requests implementing it, provided the feature is gated by a compilation flag (like we have for ed25519)

**Comment by ghost** [comment]
thanks for the reply!
